# Generated by Django 5.1.7 on 2025-03-20 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ebay', 'eBay'), ('chrono24', 'Chrono24'), ('bezel', 'Bezel'), ('grailzee', 'Grailzee')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_url', models.URLField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('listing_date', models.DateField()),
                ('additional_info', models.JSONField(default=dict)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('watch_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='inventory.watchmodel')),
            ],
        ),
    ]
