# Generated by Django 4.2.7 on 2025-04-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_status_product_availability'),
        ('market_insights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='marketdata',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='source',
            field=models.CharField(choices=[('ebay', 'eBay'), ('chrono24', 'Chrono24'), ('bezel', 'Bezel'), ('grailzee', 'Grailzee')], max_length=50),
        ),
    ]
