# Generated by Django 4.2.7 on 2025-04-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_insights', '0002_remove_marketdata_additional_info_marketdata_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
