# Generated by Django 4.2.7 on 2025-04-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_insights', '0003_marketdata_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='reference_number',
        ),
    ]
