# Generated by Django 4.2.7 on 2025-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_insights', '0005_marketdata_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='item_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
