# Generated by Django 4.2.7 on 2025-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('ADVANCED', 'Advanced'), ('PRO', 'Pro')], max_length=50),
        ),
    ]
