# Generated by Django 4.2.7 on 2025-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
