# Generated by Django 4.2.7 on 2025-04-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='availability',
        ),
    ]
