# Generated by Django 4.2.7 on 2025-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_unique_together_product_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_purchased',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
