# Generated by Django 4.2.7 on 2025-05-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_whole_price_product_wholesale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='model_name',
        ),
    ]
