# Generated by Django 4.2.7 on 2025-05-15 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('owner', 'product_id')},
        ),
    ]
