# Generated by Django 4.2.7 on 2025-05-23 13:48

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_product_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=50, validators=[inventory.models.validate_no_emojis]),
        ),
    ]
