# Generated by Django 4.2.7 on 2025-05-23 13:54

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[inventory.models.validate_no_emojis]),
        ),
    ]
