# Generated by Django 4.2.7 on 2025-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionhistory_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
