# Generated by Django 4.2.7 on 2025-05-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_unique_together_and_more'),
        ('transactions', '0003_transactionhistory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='sale_price',
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='inventory.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='transactions.transactionhistory')),
            ],
        ),
    ]
