# Generated by Django 4.2.7 on 2025-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transactionhistory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
