# Generated by Django 4.2.7 on 2025-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionhistory_trade_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='amount',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='transactionitem',
            old_name='cost_price',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='trade_name',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='name_of_trade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
