# Generated by Django 4.2.7 on 2025-05-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_recipientaddress_senderaddress_shippingconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
