# Generated by Django 4.2.7 on 2025-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shipment_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingconfig',
            name='auth_key',
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='account_id',
            field=models.CharField(default='11103', max_length=50),
        ),
    ]
