# Generated by Django 4.2.7 on 2025-05-22 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0004_remove_shippingconfig_auth_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingconfig',
            name='app_password',
            field=models.CharField(default='dLCGp2kk7X7ePUMV', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='app_username',
            field=models.CharField(default='Multi_onDemand', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_config', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='account_id',
            field=models.CharField(help_text='IFS Account ID (provided by IFS)', max_length=50),
        ),
    ]
